export const ADD_TOPPING = 'ADD_TOPPING';
export const REMOVE_TOPPING = 'REMOVE_TOPPING';
export const PIZZA_SIZE_HANDLER = 'PIZZA_SIZE_HANDLER';
export const CHECKOUT_CONTENT_HANDLER = 'CHECKOUT_CONTENT_HANDLER';
