export const ADD_TOPPING = 'ADD_TOPPING';
export const REMOVE_TOPPING = 'REMOVE_TOPPING';
export const PIZZA_SIZE_HANDLER = 'PIZZA_SIZE_HANDLER';
export const CHECKOUT_CONTENT_HANDLER = 'CHECKOUT_CONTENT_HANDLER';

export const PURCHASE_PIZZA_START = 'PURCHASE_PIZZA_START';
export const PURCHASE_PIZZA_SUCCESS = 'PURCHASE_PIZZA_SUCCESS';
export const PURCHASE_PIZZA_FAIL = 'PURCHASE_PIZZA_FAIL';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
